---
Name: silverstripe-headless
---
SilverStripe\CMS\Model\SiteTree:
  headless_fields:
    Title: title
    MenuTitle: menuTitle
    Content: content
    RelativeLink: link
    isSection: section
    SiteConfig.Title: siteTitle
SilverStripe\Assets\File:
  headless_fields:
    Title: title
    AbsoluteURL: url
